### ISSUE TITLE
opengl exception on fedora 32

### ISSUE THREAD

**Issue by XracerX** [achiwa912/tet#2]
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo

XracerX@LenovoB560:~/Games/tet$ python tet.py 
Traceback (most recent call last):
  File "/home/XracerX/.local/lib/python3.8/site-packages/arcade/application.py", line 85, in __init__
    super().__init__(width=width, height=height, caption=title,
  File "/home/XracerX/.local/lib/python3.8/site-packages/pyglet/window/xlib/__init__.py", line 173, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/XracerX/.local/lib/python3.8/site-packages/pyglet/window/__init__.py", line 603, in __init__
    config = screen.get_best_config(config)
  File "/home/XracerX/.local/lib/python3.8/site-packages/pyglet/canvas/base.py", line 194, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tet.py", line 618, in <module>
    main()
  File "tet.py", line 601, in main
    window = arcade.Window(WIDTH, HEIGHT, "Tetris")
  File "/home/XracerX/.local/lib/python3.8/site-packages/arcade/application.py", line 90, in __init__
    raise NoOpenGLException("Unable to create an OpenGL 3.3+ context. "
arcade.application.NoOpenGLException: Unable to create an OpenGL 3.3+ context. Check to make sure your system supports OpenGL 3.3 or higher.

**Comment by achiwa912** [comment]
It seems that arcade library requires OpenGL 3.3 or higher.
https://arcade.academy/get_started.html
Which OpenGL version is installed?  Run `glxinfo | grep "OpenGL version"`

**Comment by XracerX** [comment]
$ glxinfo | grep -i 'opengl version'
OpenGL version string: 2.1 Mesa 20.1.2

**Comment by achiwa912** [comment]
Unfortunately, arcade library needs OpenGL 3.3 or higher.
My Fedora 31 on VirtualBox has the same OpenGL version and the same symptom.  I don't know if you can upgrade OpenGL to 3.3 on Fedora or not but if you could, please try again.
